---
stages:
  # - prepare
  - test
  - publish

# inspired by:
#   https://github.com/academic-moodle-cooperation/moodle-local_checkmarkreport/blob/master/.gitlab-ci.yml

variables:
  DEBIAN_FRONTEND: 'noninteractive'
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"
  MOODLE_BRANCH: 'main'
  MOODLE_BEHAT_WWWROOT: 'http://localhost:8000'
  MOODLE_BEHAT_WDHOST: 'http://behat:4444/wd/hub'
  MOODLE_START_BEHAT_SERVERS: 'no'
  DB: 'mariadb'

default:
  cache:
    paths:
      - .cache
      - vendor/

  image: moodlehq/moodle-php-apache:8.3
  before_script:
    # move to container
    - mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7
    - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
    - 'curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash'
    - source ~/.bashrc
    - nvm install --default --latest-npm lts/gallium
    - composer create-project -n --no-dev --no-progress --no-ansi  --prefer-dist moodlehq/moodle-plugin-ci /opt/moodle-plugin-ci ^4
    - export PATH="/opt/moodle-plugin-ci/bin:/opt/moodle-plugin-ci/vendor/bin:$PATH"
    # TODO not always needed
    # install moodle
    # - moodle-plugin-ci install --db-host db 
    # - '{ php -S 0.0.0.0:8000 -t "$CI_PROJECT_DIR/moodle" >/dev/null 2>&1 & }'

# install dependencies:
#   stage: prepare
#   script:
#     composer install

test:
  stage: test
  services:
    # - name: selenium/standalone-chrome:3
    #   alias: behat
    - name: mariadb:11.6
      alias: db
      command:
        - '--character-set-server=utf8mb4'
        - '--collation-server=utf8mb4_unicode_ci'
        - '--innodb_file_per_table=On'
        - '--wait-timeout=28800'
        - '--skip-log-bin'
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  script:
    - composer install
    - apt update
    - apt -yqq install --no-install-suggests default-jre-headless mariadb-client
    - moodle-plugin-ci install --moodle=/opt/moodle  --db-name moodle --db-host db
    - moodle-plugin-ci phplint $CI_PROJECT_DIR
    - moodle-plugin-ci phpunit $CI_PROJECT_DIR
    - moodle-plugin-ci validate $CI_PROJECT_DIR
    - moodle-plugin-ci behat --auto-rerun 0 --profile chrome $CI_PROJECT_DIR


validate:
  stage: test
  # image: moodlehq/moodle-php-apache:7
  image: moodlehq/moodle-php-apache:8.1
  # variables:
  #   MOODLE_BRANCH: 'MOODLE_310_STABLE'
  script:
    - composer install
    # - validate-version # TODO complains about CHANGELOG.md, even if it exist double check
    - moodle-plugin-ci savepoints $CI_PROJECT_DIR

    # TODO
    # - moodle-plugin-ci phpmd
    # - moodle-plugin-ci mustache
    # - moodle-plugin-ci grunt
    # - moodle-plugin-ci phpdoc

moodle-lint:
  stage: test
  image: moodlehq/moodle-php-apache:8.1
  script:
    - composer install
    - moodle-plugin-ci phpcs $CI_PROJECT_DIR --ansi
  allow_failure: true

package plugin:
  stage: publish
  image: moodlehq/moodle-php-apache:8.1
  before_script:
    - apt update
    - apt install zip -y
  script:
    - rm -rf vendor/ .cache
    - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
    - composer install --no-dev
    - 'version=$(sed -n ''s/\s*$plugin->version\s*=\s\([0-9]*\);.*/\1/p'' version.php)'
    - 'echo "version: ${version}"'
    - 'folder="$(basename $CI_PROJECT_DIR)"'
    - 'echo "folder: ${folder}"'
    - 'cd ..'
    - zip ${CI_PROJECT_DIR}/local_auth_${version}.zip ${folder} -r -x '*.git/*'
  artifacts:
    paths:
      - local_auth_*.zip
